applications/persona/urls.py
from django.contrib import admin
from django.urls import path 


from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name ='inicio'
        ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleado.as_view(),
        name = 'empleados_all'),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadoAdmin.as_view(),
        name = 'empleados_admin'),
    path(
        'listar-by-area/<short_name>',
        views.ListByDepartament.as_view(),
        name = 'listarporarea'),
    path('listar-by-job/<job>',views.ListByJob.as_view()),
    path('buscar-empleado',views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades',views.ListHabilidadesEmpleado.as_view()),
    path(
        'detail-empleado/<pk>',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'),
    path(
        'add-empleado',
        views.EmpleadoCreateView.as_view(),
        name = 'crear'),
    path('success/',views.SuccessView.as_view(), name ='correcto'),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name ='actualizar'),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name ='borrar'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static



    

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las app departamento
    re_path('',include('applications.departamento.urls')),
    #incluimos las urls de las app persona
    re_path('',include('applications.persona.urls')),
    #incluimos las urls de las app home
    re_path('',include('applications.home.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models

from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'

    def __str__(self):
        return str(self.id) + ' - ' +self.habilidad
    

class Empleado(models.Model):
    """ tabla para empleado"""

    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120,blank = True)
    job = models.CharField('Trabajo', max_length=60,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField( blank = True)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['-first_name']
        #unique_together = ('name','short_name')

    def __str__(self):
        return str(self.id) + ' - ' +self.first_name + ' - ' + self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
            'hoja_vida',
        )

        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(
                
            )
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView )

from .models import Empleado
from .forms import EmpleadoForm

# Create your views here.

class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """

    template_name = 'inicio.html'

class ListAllEmpleado(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    context_object_name='empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        print(palabra_clave)
        return lista

class ListaEmpleadoAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name='empleados'
    model = Empleado



class ListByDepartament(ListView):
    template_name = 'persona/list_by_departament.html'
    
    def get_queryset(self):
        area = self.kwargs['short_name']
        lista = Empleado.objects.filter(
         departamento__short_name = area
    )
        return lista


class ListByJob(ListView):
    template_name = 'persona/list_by_job.html'
    
    def get_queryset(self):
        tarea = self.kwargs['job']
        lista = Empleado.objects.filter(
            job = tarea
    )
        return lista


class ListEmpleadoByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/list_habilidades_empleado.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        id_clave = self.request.GET.get("kid",6)
        empleado = Empleado.objects.get(id = id_clave)
        return empleado.habilidades.all()



class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail_empleado.html'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context
    


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')


    def form_valid(self, form):
        empleado = form.save(commit= False)
        empleado.full_name = empleado.first_name+' '+empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)



class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = ['first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'
        ]
    success_url = reverse_lazy('persona_app:empleados_admin')


   
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"

    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina Registro Empleado {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleados</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    {{form.as_p}}
                </div>
                <!-- <div class="cell large-6">
                    <label>Apellido
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades
                        {{form.habilidades}}
                    </label>
                </div> -->
                <div class="cell">
                    <button type="submit" class="success  button">Crear</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1>qweqwe</h1>

<form method="GET"> {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese id aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultado</h3>

<ul>
    {% for e in empleados %}
      <li>{{e}}</li>
    {%endfor%}
</ul>

templates/persona/delete.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Borrar empleado {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Borrar Empleado {{ object.first_name }}</h1>
            <form class="cell" method="POST">{% csrf_token %}

                <div class="callout">
                    <h5>Desesa eliminar este empleado?</h5>
                    <button type="submit" class="alert button">Confirmar</button>
                </div>
            </form>      
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} {{object.full_name}} {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-6 card" style="width: 600px; margin-top: 15px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>
            
            {% if empleado.avatar %}
                <img src="{{empleado.avatar.url}}">
            {% else %}
                <img src="{% static 'img/1.jpg' %}">
            {% endif %}
                
            
            <div class="card-section">
              <h4>{{empleado.full_name}}</h4>
              <p>{{empleado.first_name}}</p>
              <p>{{empleado.last_name}}</p>
              <p>{{empleado.departamento.short_name}}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all %}
                        <li>{{h.habilidad}}</li>
                    {% endfor %}     
              </ul>
            </div>
        </div>
    </div>

</div>


{% endblock content %}

templates/persona/list_all.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina de inicio de empleados {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
              <div class="cell large-7">
                  <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
              </div>
              <div class="cell large-2">
                  <button type="submit" class="success button">Save</button>
              </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>          
                </thead>
                <tbody>
                    {%for e in empleados%}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.pk %}">Ver</a></td>
                      </tr>
                      {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">                    
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                              <a href="?page={{page_obj.previous_page_number}}">Atras </a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range  %}
                            {% ifequal pagina page_obj.number %} 
                                <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}" aria-label="Page 1">{{pagina}}</a></li>
                            {% endifequal %}
                        {% endfor %}
                          
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">page</span></a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/list_by_departament.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Lista por Departamento {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="gid-x">
        <div class="cell">Empleados por Area</div>
        <div class="cell">
            <table>
              <thead>
                  <tr>
                      <th width="200">ID</th>
                      <th>NOMBRES</th>
                      <th width="150">APELLIDOS</th>
                      <th width="150">DEPARTAMENTO</th>
                      <th width="150">ACCION</th>
                  </tr>          
              </thead>
              <tbody>
                  {%for e in object_list%}
                  <tr>
                      <td>{{e.id}}</td>
                      <td>{{e.first_name}}</td>
                      <td>{{e.last_name}}</td>
                      <td>{{e.departamento}}</td>
                      <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.pk %}">Ver</a></td>
                    </tr>
                    {%endfor%}
              </tbody>
            </table>
         
        </div>
    </div>

</div>



{% endblock content %}

<ul>
  {%for e in object_list%}
    <li>{{e}}</li>
  {%endfor%}
</ul>

templates/persona/list_by_job.html
<h1>lista empleado por trabajo</h1>

<ul>
    {%for e in object_list%}
      <li>{{e}}</li>
    {%endfor%}
</ul>

templates/persona/list_habilidades_empleado.html
<h1>habilidades</h1>

<form method="GET"> {% csrf_token %}
  <input type="number" id="kid" name="kid" placeholder="Ingrese id aqui">
  <button type="submit">Buscar</button>
</form>

<h3>Lista habulidades</h3>


<ul>
    {%for e in habilidades%}
      <li>{{e}}</li>
    {%endfor%}
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina de inicio de empleados {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>          
                </thead>
                <tbody>
                    {%for e in empleados%}
                    <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:actualizar' e.pk %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:borrar' e.pk %}">Eliminar</a>
                        </td>
                      </tr>
                      {%endfor%}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">                    
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                              <a href="?page={{page_obj.previous_page_number}}">Atras </a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range  %}
                            {% ifequal pagina page_obj.number %} 
                                <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}" aria-label="Page 1">{{pagina}}</a></li>
                            {% endifequal %}
                        {% endfor %}
                          
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente <span class="show-for-sr">page</span></a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/success.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina de inicio de empleados {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Borrar Empleado</h1>
        <div class="cell">
            <div data-alert class="alert-box success radius">
                Operacion Exitosa.
                <a href="#" class="close">&times;</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/persona/update.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina Actualizar Empleado {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Actualizar Empleados</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success  button">Guardar</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

{% endblock content %}