applications/departamento/urls.py
from django.contrib import admin
from django.urls import path 

from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/',
        views.NewDepartamentoView.as_view(),
        name = 'agregardepartamento'),
    path('list-departamento/',
        views.DepartamentoListView.as_view(),
        name = 'listardepartamento'),
  
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path 


from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name ='inicio'
        ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleado.as_view(),
        name = 'empleados_all'),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadoAdmin.as_view(),
        name = 'empleados_admin'),
    path(
        'listar-by-area/<short_name>',
        views.ListByDepartament.as_view(),
        name = 'listarporarea'),
    path('listar-by-job/<job>',views.ListByJob.as_view()),
    path('buscar-empleado',views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades',views.ListHabilidadesEmpleado.as_view()),
    path(
        'detail-empleado/<pk>',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'),
    path(
        'add-empleado',
        views.EmpleadoCreateView.as_view(),
        name = 'crear'),
    path('success/',views.SuccessView.as_view(), name ='correcto'),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name ='actualizar'),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name ='borrar'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static



    

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las app departamento
    re_path('',include('applications.departamento.urls')),
    #incluimos las urls de las app persona
    re_path('',include('applications.persona.urls')),
    #incluimos las urls de las app home
    re_path('',include('applications.home.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:inicio' %}">Inicio</a></li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:listardepartamento' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin'%}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:agregardepartamento'%}">Agregar Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href="{% url 'persona_app:crear'%}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
</div>