applications/departamento/urls.py
from django.contrib import admin
from django.urls import path 

from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/',
        views.NewDepartamentoView.as_view(),
        name = 'agregardepartamento'),
    path('list-departamento/',
        views.DepartamentoListView.as_view(),
        name = 'listardepartamento'),
  
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path 


from . import views

app_name = 'persona_app'

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name ='inicio'
        ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleado.as_view(),
        name = 'empleados_all'),
    path(
        'lista-empleados-admin/',
        views.ListaEmpleadoAdmin.as_view(),
        name = 'empleados_admin'),
    path(
        'listar-by-area/<short_name>',
        views.ListByDepartament.as_view(),
        name = 'listarporarea'),
    path('listar-by-job/<job>',views.ListByJob.as_view()),
    path('buscar-empleado',views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades',views.ListHabilidadesEmpleado.as_view()),
    path(
        'detail-empleado/<pk>',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'),
    path(
        'add-empleado',
        views.EmpleadoCreateView.as_view(),
        name = 'crear'),
    path('success/',views.SuccessView.as_view(), name ='correcto'),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name ='actualizar'),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name ='borrar'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static



    

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las app departamento
    re_path('',include('applications.departamento.urls')),
    #incluimos las urls de las app persona
    re_path('',include('applications.persona.urls')),
    #incluimos las urls de las app home
    re_path('',include('applications.home.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20,unique = True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        ordering = ['-name']
        unique_together = ('name','short_name')


    def __str__(self):
        return str(self.id) + ' - ' +self.name + ' - ' + self.short_name


       

applications/departamento/forms.py
from django import forms

class NewDepartametoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render

from django.urls import reverse_lazy

from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Empleado

from .models import Departamento

from .forms import NewDepartametoForm
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'departamento'

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartametoForm
    success_url = '/'

    def form_valid(self, form):
        print('========estamos en el form valid=============')

        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shortname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Lista Departamento {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>
                    {%for e in departamento%}
                        <tr>
                            <td>{{e.id}}</td>
                            <td>{{e.name}}</td>
                            <td>{{e.short_name}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:listarporarea' e.short_name%}">Ver Empleados</a></td>
                        </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %} 

{%load static%}

{% block title %} Pagina Agregar Departamento {% endblock title %}


{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Nuevo Departamento</h1>
        <div class="cell">
            <form class="cell callout grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres
                        {{form.nombre}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellido
                        {{form.apellido}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo
                        {{form.shortname}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Departamento
                        {{form.departamento}}
                    </label>
                </div>
                

                <div class="cell">
                    <button type="submit" class="success  button">Guardar</button>
                </div>

                
            </form>
            
        </div>
    </div>
</div>

{% endblock content %}